project:
  base_path: ./
  filters:
    - ignore:
      - ".idea"
      - .git
      - node_modules
      - ai_helper
      - .ai_helper
      - "spike"
      - config.yml
      - doc
      - "**/*.png"
      - "**/.DS_Store"
      - "**/LICENSE.txt"
      - "**/package-lock.json"

input:
  instruction: |
    我希望 修改README.md加入$additional_items的内容
output:     
  prompt:
    path: .ai_helper/prompt_builder/output/working
    backup_path: .ai_helper/prompt_builder/output/backup