project:
  base_path: ./
  filters:
    - ignore:
      - ".idea"
      - .git
      - node_modules
      - ai_helper
      - .ai_helper
      - "spike"
      - config.yml
      - doc
      - "**/*.png"
      - "**/.DS_Store"
      - "**/LICENSE.txt"
      - "**/package-lock.json"

input:
  instruction: |
    我希望 index.js 提供的两个API都有一个Sync版，因为我有些场景需要Sync。但标记为deperacate，因为我未来准备放弃支持。
output:     
  prompt:
    path: .ai_helper/prompt_builder/output/working
    backup_path: .ai_helper/prompt_builder/output/backup