project:
  base_path: ./
  filters:
    - ignore:
      - ".idea"
      - .git
      - node_modules
      - ai_helper
      - .ai_helper
      - "spike"
      - config.yml
      - doc
      - "**/*.png"
      - "**/.DS_Store"
      - "**/LICENSE.txt"
      - "**/package-lock.json"

input:
  instruction: |
    我希望 index.js导出的不是只有一个 loadYamlFile，还要有一个 loadYaml，它支持的是文本
output:     
  prompt:
    path: .ai_helper/prompt_builder/output/working
    backup_path: .ai_helper/prompt_builder/output/backup